apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_DATABASE: mydatabase
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
